### ISSUE TITLE
Infinite loop in DIF instruction.

### ISSUE THREAD

**Issue by michalgw** [jdykstra/ucsd-psystem-vm#3]
Implementation of the DIF instruction contains an endless loop:
https://github.com/jdykstra/ucsd-psystem-vm/blob/43c8fb9fc86dfba3a4ae78ec1256630fa533b388/ucsdpsys_vm/main.c#L2200-L2201

**Comment by jdykstra** [comment]
Thanks for the report.  I should be able to test and commit the fix by the weekend.

I'm curious.  Did you find this with a code checker, or trip across it while actually using the P-System tools?  And if the later, for what?  I see lots of people cloning the repos, but I don't know what my "customers" are doing with it.

**Comment by michalgw** [comment]
Actually, I'm porting this code to Pascal (using Free Pascal). Finally, I would like to create a vm for Atari 8-bit platform using MadPascal (https://github.com/tebe6502/Mad-Pascal).
